// commandr/frontend/src/components/ChatMessage.vue
<script setup lang="ts">
defineProps<{
  role: string
  content: string
}>()
</script>

<template>
  <div
    :class="[
      'p-4 rounded-lg',
      role === 'user' ? 'bg-blue-600 ml-12' : 'bg-gray-700 mr-12'
    ]"
  >
    <div class="text-sm font-semibold mb-2 text-gray-200">
      {{ role === 'user' ? 'You' : 'Assistant' }}
    </div>
    <div class="text-white whitespace-pre-wrap">{{ content }}</div>
  </div>
</template>

// commandr/frontend/src/components/ChatMessage.tsx
import React from 'react';
import '../styles/theme.css';

interface ChatMessageProps {
    role: string;
    content: string;
}

export const ChatMessage: React.FC<ChatMessageProps> = ({ role, content }) => {
    return (
        <div className={`p-4 mb-4 rounded-lg ${role === 'user' ? 'bg-blue-600' : 'metallic-background'}`}>
            <div className="text-sm font-semibold mb-2">
                {role === 'user' ? 'You' : 'Assistant'}
            </div>
            <div className="text-white">
                {content}
            </div>
        </div>
    );
};


export default ChatMessage;
