// commandr/frontend/src/components/ChatInput.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{
  disabled?: boolean
}>()

const emit = defineEmits<{
  (e: 'send', value: string): void
}>()

const message = ref('')

function handleSubmit() {
  if (message.value.trim() && !props.disabled) {
    emit('send', message.value.trim())
    message.value = ''
  }
}

function handleKeypress(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    handleSubmit()
  }
}
</script>

<template>
  <div class="p-4 bg-gray-700">
    <div class="flex space-x-4">
      <textarea
        v-model="message"
        :disabled="disabled"
        class="flex-1 p-2 bg-gray-800 text-white rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"
        :class="{ 'opacity-50': disabled }"
        rows="3"
        :placeholder="disabled ? 'Please wait...' : 'Type your message...'"
        @keypress="handleKeypress"
      />
      <button
        :disabled="disabled || !message.trim()"
        class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
        :class="{ 'opacity-50': disabled || !message.trim() }"
        @click="handleSubmit"
      >
        Send
      </button>
    </div>
  </div>
</template>

// commandr/frontend/src/components/ChatInput.tsx
import { KeyboardEvent, useState } from 'react';

interface ChatInputProps {
  onSend: (message: string) => void;
  disabled?: boolean;
}

export default function ChatInput({ onSend }: ChatInputProps) {
  const [message, setMessage] = useState('');

  const handleSubmit = () => {
    if (message.trim()) {
      onSend(message.trim());
      setMessage('');
    }
  };

  const handleKeyPress = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div className="p-4 bg-gray-700">
      <div className="flex space-x-4">
        <textarea
          className="flex-1 p-2 bg-gray-800 text-white rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"
          rows={3}
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          onKeyPress={handleKeyPress}
          placeholder="Type your message..."
        />
        <button
          onClick={handleSubmit}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          Send
        </button>
      </div>
    </div>
  );
}
